asset: letsdmmf.zip
tap: yujong-lee/homebrew-tab/letsdmmf.rb
template: >
  class letsdmmf < Formula
    desc        "$REPO_DESCRIPTION"
    homepage    "$REPO_WEBITE"
    version     "$STABLE_VERSION"
    url         "$STABLE_ASSET_URL"
    sha256      "$STABLE_ASSET_SHA256"
    depends_on  "jless"

    def install
      bin.install "letsdmmf"
    end
  end
