[package]
name = "letsdmmf"
version = "0.2.1"
edition = "2021"

[dependencies]
datamodel = { git = "https://github.com/prisma/prisma-engines" }
dmmf = { git = "https://github.com/prisma/prisma-engines" }
clap = { version = "3.1.6", features = ["derive"] }
