[package]
name = "letsdmmf"
version = "0.1.0"
edition = "2021"

[dependencies]
datamodel = { git = "https://github.com/prisma/prisma-engines" }
dmmf = { git = "https://github.com/prisma/prisma-engines" }
